# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watch_time.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dog(object):
    def setupUi(self, dog):
        dog.setObjectName("dog")
        dog.resize(1800, 952)
        self.tabWidget = QtWidgets.QTabWidget(dog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 50, 1721, 921))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(30, 60))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(9, 90, 881, 721))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(1420, 60, 281, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(140, 10, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 115, 86))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(740, 830, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 40, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_9.setGeometry(QtCore.QRect(910, 90, 491, 721))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(4)
        self.tableWidget_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(930, 40, 141, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(1120, 50, 81, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(1200, 50, 131, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 70, 1571, 481))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(13)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 30, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 560, 1571, 341))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(13)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(180, 30, 141, 31))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(30, 70, 1241, 321))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(12)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(11, item)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_5.setGeometry(QtCore.QRect(30, 420, 1241, 321))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(12)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(11, item)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_7.setGeometry(QtCore.QRect(1340, 70, 351, 701))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(3)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 780, 131, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 30, 111, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_6.setGeometry(QtCore.QRect(160, 30, 111, 31))
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 30, 121, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_8.setGeometry(QtCore.QRect(250, 30, 111, 31))
        self.checkBox_8.setObjectName("checkBox_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 80, 1641, 261))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 2, 1, 1)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(3)
        self.tableWidget_8.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget_8, 1, 0, 1, 1)
        self.tableWidget_10 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(3)
        self.tableWidget_10.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget_10, 1, 1, 1, 1)
        self.tableWidget_11 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(3)
        self.tableWidget_11.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_11.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_11.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget_11, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 40, 131, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tableWidget_12 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_12.setGeometry(QtCore.QRect(40, 380, 1031, 192))
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(9)
        self.tableWidget_12.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_12.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 70, 292, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBox_3)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(420, 70, 231, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(420, 180, 231, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(670, 70, 231, 101))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(80, 360, 311, 227))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_010 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_010.setFont(font)
        self.label_010.setObjectName("label_010")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_010)
        self.lineEdit_08 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_08.setFont(font)
        self.lineEdit_08.setObjectName("lineEdit_08")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_08)
        self.label_011 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_011.setFont(font)
        self.label_011.setObjectName("label_011")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_011)
        self.lineEdit_013 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_013.setFont(font)
        self.lineEdit_013.setObjectName("lineEdit_013")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_013)
        self.label_012 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_012.setFont(font)
        self.label_012.setObjectName("label_012")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_012)
        self.lineEdit_014 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_014.setFont(font)
        self.lineEdit_014.setObjectName("lineEdit_014")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_014)
        self.label_019 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_019.setFont(font)
        self.label_019.setObjectName("label_019")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_019)
        self.lineEdit_015 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_015.setFont(font)
        self.lineEdit_015.setObjectName("lineEdit_015")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_015)
        self.label_020 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_020.setFont(font)
        self.label_020.setObjectName("label_020")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_020)
        self.lineEdit_016 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_016.setFont(font)
        self.lineEdit_016.setObjectName("lineEdit_016")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_016)
        self.label_021 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_021.setFont(font)
        self.label_021.setObjectName("label_021")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_021)
        self.lineEdit_017 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_017.setFont(font)
        self.lineEdit_017.setObjectName("lineEdit_017")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_017)
        self.label_022 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_022.setFont(font)
        self.label_022.setObjectName("label_022")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_022)
        self.lineEdit_018 = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_018.setFont(font)
        self.lineEdit_018.setObjectName("lineEdit_018")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_018)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_6.setGeometry(QtCore.QRect(20, 620, 1151, 192))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(11)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(10, item)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_13 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_13.setGeometry(QtCore.QRect(40, 80, 591, 121))
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.setColumnCount(5)
        self.tableWidget_13.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_13.setHorizontalHeaderItem(4, item)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_2.setGeometry(QtCore.QRect(740, 80, 251, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_9.setGeometry(QtCore.QRect(30, 30, 131, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_10.setGeometry(QtCore.QRect(30, 60, 131, 16))
        self.checkBox_10.setObjectName("checkBox_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_3.setGeometry(QtCore.QRect(740, 200, 251, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_11.setGeometry(QtCore.QRect(30, 30, 131, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_12.setGeometry(QtCore.QRect(30, 60, 131, 16))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_13.setGeometry(QtCore.QRect(30, 90, 131, 16))
        self.checkBox_13.setObjectName("checkBox_13")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(110, 30, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(190, 30, 54, 21))
        self.label_22.setObjectName("label_22")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_9.setGeometry(QtCore.QRect(740, 340, 151, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_20 = QtWidgets.QLabel(self.tab_7)
        self.label_20.setGeometry(QtCore.QRect(50, 50, 101, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(180, 50, 61, 31))
        self.label_21.setObjectName("label_21")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_8.setGeometry(QtCore.QRect(240, 50, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")

        self.retranslateUi(dog)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(dog)

    def retranslateUi(self, dog):
        _translate = QtCore.QCoreApplication.translate
        dog.setWindowTitle(_translate("dog", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dog", "代码"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dog", "价格"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dog", "PB"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("dog", "股息（税前）"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("dog", "股息率（税前）"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("dog", "分红公告期"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("dog", "flitter排名"))
        self.groupBox.setTitle(_translate("dog", "行情接口选择"))
        self.label.setText(_translate("dog", "行情接口对所有页面有效"))
        self.label_2.setText(_translate("dog", "三选一"))
        self.checkBox_4.setText(_translate("dog", "通达信"))
        self.checkBox_5.setText(_translate("dog", "tushare"))
        self.checkBox_7.setText(_translate("dog", "joinquant"))
        self.pushButton.setText(_translate("dog", "更新银行行业信息表"))
        self.pushButton_2.setText(_translate("dog", "刷新银行分红信息及排名表"))
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("dog", "A 代码"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("dog", "HK 代码"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("dog", "H/A"))
        self.pushButton_6.setText(_translate("dog", "刷新H/A溢价"))
        self.label_10.setText(_translate("dog", "HKD/RMB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dog", "银行"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("dog", "代码"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("dog", "当前价格"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("dog", "昨收价"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("dog", "pb"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("dog", "pb min"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("dog", "pb_min 日期"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("dog", "pb 5%分位"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("dog", "pb 10%分位"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("dog", "pb中位数"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("dog", "pb max"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("dog", "pb_max 日期"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("dog", "pb 方差"))
        self.pushButton_3.setText(_translate("dog", "刷新"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("dog", "代码"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("dog", "当前价格"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("dog", "昨收价"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("dog", "pe"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("dog", "pe min"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("dog", "pe_min 日期"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("dog", "pe 5%分位"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("dog", "pe 10%分位"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("dog", "pe中位数"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("dog", "pe max"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("dog", "pe_max 日期"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("dog", "pe 方差"))
        self.checkBox.setText(_translate("dog", "只分析重点关注标的"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dog", "券商"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("dog", "代码"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("dog", "价格/date"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("dog", "pb"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("dog", "pb min"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("dog", "pb min date"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("dog", "pb 5%"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("dog", "pb 10%"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("dog", "pb 中位数"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("dog", "pb max"))
        item = self.tableWidget_4.horizontalHeaderItem(10)
        item.setText(_translate("dog", "pb max date"))
        item = self.tableWidget_4.horizontalHeaderItem(11)
        item.setText(_translate("dog", "std"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("dog", "代码"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("dog", "价格/date"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("dog", "pe"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("dog", "pe min"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("dog", "pe min date"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("dog", "pe 5%"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("dog", "pe 10%"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("dog", "pe 中位数"))
        item = self.tableWidget_5.horizontalHeaderItem(9)
        item.setText(_translate("dog", "pe max"))
        item = self.tableWidget_5.horizontalHeaderItem(10)
        item.setText(_translate("dog", "pe max date"))
        item = self.tableWidget_5.horizontalHeaderItem(11)
        item.setText(_translate("dog", "std"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("dog", "代码"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("dog", "名称"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("dog", "权重"))
        self.pushButton_5.setText(_translate("dog", "选择分析指数"))
        self.checkBox_2.setText(_translate("dog", "最近5年"))
        self.checkBox_6.setText(_translate("dog", "2010年始"))
        self.pushButton_8.setText(_translate("dog", "刷新"))
        self.checkBox_8.setText(_translate("dog", "2011年始"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("dog", "指数估值分析"))
        self.label_11.setText(_translate("dog", "沪深300 VS 中证500"))
        self.label_12.setText(_translate("dog", "沪深300 VS 创业板"))
        self.label_19.setText(_translate("dog", "沪深300 VS 创业板50"))
        item = self.tableWidget_8.verticalHeaderItem(0)
        item.setText(_translate("dog", "二八标准"))
        item = self.tableWidget_8.verticalHeaderItem(1)
        item.setText(_translate("dog", "二八plus"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("dog", "结果"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("dog", "当前点位"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("dog", "比较日点位"))
        item = self.tableWidget_10.verticalHeaderItem(0)
        item.setText(_translate("dog", "二八标准"))
        item = self.tableWidget_10.verticalHeaderItem(1)
        item.setText(_translate("dog", "二八plus"))
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("dog", "结果"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("dog", "当前点位"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("dog", "比较日点位"))
        item = self.tableWidget_11.verticalHeaderItem(0)
        item.setText(_translate("dog", "二八标准"))
        item = self.tableWidget_11.verticalHeaderItem(1)
        item.setText(_translate("dog", "二八plus"))
        item = self.tableWidget_11.horizontalHeaderItem(0)
        item.setText(_translate("dog", "结果"))
        item = self.tableWidget_11.horizontalHeaderItem(1)
        item.setText(_translate("dog", "当前点位"))
        item = self.tableWidget_11.horizontalHeaderItem(2)
        item.setText(_translate("dog", "比较日点位"))
        self.pushButton_7.setText(_translate("dog", "刷新轮动"))
        item = self.tableWidget_12.horizontalHeaderItem(0)
        item.setText(_translate("dog", "code"))
        item = self.tableWidget_12.horizontalHeaderItem(1)
        item.setText(_translate("dog", "name"))
        item = self.tableWidget_12.horizontalHeaderItem(2)
        item.setText(_translate("dog", "新建列"))
        item = self.tableWidget_12.horizontalHeaderItem(3)
        item.setText(_translate("dog", "比较值"))
        item = self.tableWidget_12.horizontalHeaderItem(4)
        item.setText(_translate("dog", "比对"))
        item = self.tableWidget_12.horizontalHeaderItem(5)
        item.setText(_translate("dog", "比较值"))
        item = self.tableWidget_12.horizontalHeaderItem(6)
        item.setText(_translate("dog", "新建列"))
        item = self.tableWidget_12.horizontalHeaderItem(7)
        item.setText(_translate("dog", "比较值"))
        item = self.tableWidget_12.horizontalHeaderItem(8)
        item.setText(_translate("dog", "date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("dog", "指数轮动"))
        self.label_3.setText(_translate("dog", "AU："))
        self.label_4.setText(_translate("dog", "AG："))
        self.label_5.setText(_translate("dog", "AU/AG:"))
        self.pushButton_4.setText(_translate("dog", "手动刷新"))
        self.label_6.setText(_translate("dog", "time："))
        self.checkBox_3.setText(_translate("dog", "自动刷新"))
        self.label_7.setText(_translate("dog", "AU"))
        self.label_8.setText(_translate("dog", "卖一价"))
        self.label_9.setText(_translate("dog", "买一价"))
        self.label_13.setText(_translate("dog", "AG"))
        self.label_14.setText(_translate("dog", "卖一价"))
        self.label_15.setText(_translate("dog", "买一价"))
        self.label_16.setText(_translate("dog", "AG/AG"))
        self.label_17.setText(_translate("dog", "做多"))
        self.label_18.setText(_translate("dog", "做空"))
        self.label_010.setText(_translate("dog", "做多买入线："))
        self.label_011.setText(_translate("dog", "做多卖出线："))
        self.label_012.setText(_translate("dog", "做空买入线："))
        self.label_019.setText(_translate("dog", "做空卖出线："))
        self.label_020.setText(_translate("dog", "统计周期："))
        self.label_021.setText(_translate("dog", "历史数据最后日期："))
        self.label_022.setText(_translate("dog", "今日："))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("dog", "多-buy"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("dog", "多-sell"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("dog", "空-buy"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("dog", "空-sell"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("dog", "max"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("dog", "min"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("dog", "均值"))
        item = self.tableWidget_6.horizontalHeaderItem(7)
        item.setText(_translate("dog", "方差"))
        item = self.tableWidget_6.horizontalHeaderItem(8)
        item.setText(_translate("dog", "25%"))
        item = self.tableWidget_6.horizontalHeaderItem(9)
        item.setText(_translate("dog", "50%"))
        item = self.tableWidget_6.horizontalHeaderItem(10)
        item.setText(_translate("dog", "75%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("dog", "gold"))
        item = self.tableWidget_13.horizontalHeaderItem(0)
        item.setText(_translate("dog", "code"))
        item = self.tableWidget_13.horizontalHeaderItem(1)
        item.setText(_translate("dog", "name"))
        item = self.tableWidget_13.horizontalHeaderItem(2)
        item.setText(_translate("dog", "当前价格"))
        item = self.tableWidget_13.horizontalHeaderItem(3)
        item.setText(_translate("dog", "监控阈值"))
        item = self.tableWidget_13.horizontalHeaderItem(4)
        item.setText(_translate("dog", "折溢价"))
        self.groupBox_2.setTitle(_translate("dog", "刷新方式"))
        self.checkBox_9.setText(_translate("dog", "自动刷新"))
        self.checkBox_10.setText(_translate("dog", "手动刷新"))
        self.groupBox_3.setTitle(_translate("dog", "自动刷新周期"))
        self.checkBox_11.setText(_translate("dog", "1分钟"))
        self.checkBox_12.setText(_translate("dog", "3分钟"))
        self.checkBox_13.setText(_translate("dog", "5分钟"))
        self.comboBox.setItemText(0, _translate("dog", "1"))
        self.comboBox.setItemText(1, _translate("dog", "3"))
        self.comboBox.setItemText(2, _translate("dog", "5"))
        self.comboBox.setItemText(3, _translate("dog", "10"))
        self.label_22.setText(_translate("dog", "分钟"))
        self.pushButton_9.setText(_translate("dog", "刷新"))
        self.label_20.setText(_translate("dog", "鹏华前海REIT"))
        self.label_21.setText(_translate("dog", "告警阈值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("dog", "捡漏监控"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("dog", "期现套利"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dog = QtWidgets.QWidget()
    ui = Ui_dog()
    ui.setupUi(dog)
    dog.show()
    sys.exit(app.exec_())

