# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convertbond.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ant(object):
    def setupUi(self, ant):
        ant.setObjectName("ant")
        ant.resize(1800, 952)
        self.tabWidget = QtWidgets.QTabWidget(ant)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1731, 941))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(50, 30, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(9, 50, 1661, 721))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 790, 1381, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 40, 821, 521))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(860, 500, 511, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(1420, 40, 281, 111))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(190, 40, 71, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(190, 60, 81, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(860, 310, 511, 121))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(853, 40, 520, 220))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tableWidget_3)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tableWidget_4)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(1420, 220, 192, 326))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_7)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_8)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lineEdit_9)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lineEdit_6)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lineEdit_10)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.pushButton_5)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(870, 470, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 570, 821, 331))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_8.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(860, 670, 101, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(ant)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ant)

    def retranslateUi(self, ant):
        _translate = QtCore.QCoreApplication.translate
        ant.setWindowTitle(_translate("ant", "Form"))
        self.checkBox.setText(_translate("ant", "监测"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ant", "监测"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ant", "代码"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ant", "债券名称"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ant", "正股名称"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ant", "正股代码"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ant", "PB"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ant", "评级"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ant", "转股价"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ant", "回售价"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ant", "强赎价"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ant", "到期日"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ant", "剩余年限"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("ant", "是否到转股期"))
        self.label.setText(_translate("ant", "源文件"))
        self.label_2.setText(_translate("ant", "目标文件"))
        self.pushButton.setText(_translate("ant", "可转债基本信息表转换"))
        self.pushButton_3.setText(_translate("ant", "更新转股期记录"))
        self.pushButton_2.setText(_translate("ant", "显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ant", "债券基本信息"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("ant", "监视"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("ant", "债券编码"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("ant", "债券名称"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("ant", "转股溢价"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("ant", "正股代码"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("ant", "正股名称"))
        self.pushButton_4.setText(_translate("ant", "刷新全表"))
        self.groupBox.setTitle(_translate("ant", "GroupBox"))
        self.checkBox_2.setText(_translate("ant", "自动交易"))
        self.checkBox_3.setText(_translate("ant", "手动交易"))
        self.checkBox_4.setText(_translate("ant", "通达信"))
        self.checkBox_5.setText(_translate("ant", "tushare"))
        self.checkBox_6.setText(_translate("ant", "登录交易接口"))
        self.checkBox_7.setText(_translate("ant", "joinquant"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("ant", "卖2"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("ant", "卖1"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("ant", "买1"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("ant", "买2"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("ant", "价格"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("ant", "量"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("ant", "卖2"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("ant", "卖1"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("ant", "买1"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("ant", "买2"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("ant", "价格"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("ant", "量"))
        self.label_5.setText(_translate("ant", "转债代码"))
        self.label_3.setText(_translate("ant", "买入转债数量"))
        self.label_6.setText(_translate("ant", "买入转债价格"))
        self.label_7.setText(_translate("ant", "正股代码"))
        self.label_4.setText(_translate("ant", "卖出正股数量"))
        self.label_8.setText(_translate("ant", "卖出正股价格"))
        self.pushButton_5.setText(_translate("ant", "交易"))
        self.label_9.setText(_translate("ant", "交易日志"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("ant", "债券编码"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("ant", "债券名称"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("ant", "转股溢价"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("ant", "正股代码"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("ant", "正股名称"))
        self.checkBox_8.setText(_translate("ant", "监测"))
        self.pushButton_6.setText(_translate("ant", "刷新精选表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ant", "实时运行监视"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ant = QtWidgets.QWidget()
    ui = Ui_ant()
    ui.setupUi(ant)
    ant.show()
    sys.exit(app.exec_())

