# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watchdog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_watchdog(object):
    def setupUi(self, watchdog):
        watchdog.setObjectName("watchdog")
        watchdog.resize(1814, 956)
        self.tableWidget = QtWidgets.QTableWidget(watchdog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 40, 881, 791))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton_9 = QtWidgets.QPushButton(watchdog)
        self.pushButton_9.setGeometry(QtCore.QRect(930, 330, 31, 141))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(watchdog)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 910, 191, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.layoutWidget = QtWidgets.QWidget(watchdog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 860, 838, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(watchdog)
        self.tableWidget_2.setGeometry(QtCore.QRect(970, 40, 831, 791))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        self.pushButton_8 = QtWidgets.QPushButton(watchdog)
        self.pushButton_8.setGeometry(QtCore.QRect(1000, 860, 121, 23))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(watchdog)
        QtCore.QMetaObject.connectSlotsByName(watchdog)

    def retranslateUi(self, watchdog):
        _translate = QtCore.QCoreApplication.translate
        watchdog.setWindowTitle(_translate("watchdog", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("watchdog", "code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("watchdog", "name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("watchdog", "低价买入预警"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("watchdog", "高价卖出预警"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("watchdog", "实时价格"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("watchdog", "预警是否弹窗"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("watchdog", "time"))
        self.pushButton_9.setText(_translate("watchdog", "《"))
        self.pushButton_11.setText(_translate("watchdog", "更新监控股票"))
        self.pushButton.setText(_translate("watchdog", "运行"))
        self.pushButton_2.setText(_translate("watchdog", "终止运行"))
        self.pushButton_4.setText(_translate("watchdog", "添加监控信息"))
        self.pushButton_5.setText(_translate("watchdog", "完成添加"))
        self.pushButton_10.setText(_translate("watchdog", "删除记录"))
        self.pushButton_3.setText(_translate("watchdog", "将表格信息存入csv"))
        self.label.setText(_translate("watchdog", "行情扫描周期"))
        self.comboBox.setItemText(0, _translate("watchdog", "5"))
        self.comboBox.setItemText(1, _translate("watchdog", "10"))
        self.comboBox.setItemText(2, _translate("watchdog", "20"))
        self.comboBox.setItemText(3, _translate("watchdog", "30"))
        self.comboBox.setItemText(4, _translate("watchdog", "60"))
        self.comboBox.setItemText(5, _translate("watchdog", "90"))
        self.comboBox.setItemText(6, _translate("watchdog", "120"))
        self.comboBox.setItemText(7, _translate("watchdog", "150"))
        self.comboBox.setItemText(8, _translate("watchdog", "180"))
        self.comboBox.setItemText(9, _translate("watchdog", "210"))
        self.comboBox.setItemText(10, _translate("watchdog", "240"))
        self.comboBox.setItemText(11, _translate("watchdog", "300"))
        self.label_2.setText(_translate("watchdog", " s"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("watchdog", "转债code"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("watchdog", "转债名称"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("watchdog", "转债价格"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("watchdog", "转股价"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("watchdog", "pb"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("watchdog", "到期时间"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("watchdog", "溢价率"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("watchdog", "波动率"))
        self.pushButton_8.setText(_translate("watchdog", "手动刷新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    watchdog = QtWidgets.QWidget()
    ui = Ui_watchdog()
    ui.setupUi(watchdog)
    watchdog.show()
    sys.exit(app.exec_())

