# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watchdog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_watchdog(object):
    def setupUi(self, watchdog):
        watchdog.setObjectName("watchdog")
        watchdog.resize(1822, 956)
        self.tableWidget = QtWidgets.QTableWidget(watchdog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 40, 951, 791))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tabWidget = QtWidgets.QTabWidget(watchdog)
        self.tabWidget.setGeometry(QtCore.QRect(1020, 40, 781, 791))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 741, 731))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 20, 751, 731))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(20, 20, 751, 721))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.layoutWidget = QtWidgets.QWidget(watchdog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 860, 487, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.layoutWidget1 = QtWidgets.QWidget(watchdog)
        self.layoutWidget1.setGeometry(QtCore.QRect(1060, 850, 244, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)

        self.retranslateUi(watchdog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(watchdog)

    def retranslateUi(self, watchdog):
        _translate = QtCore.QCoreApplication.translate
        watchdog.setWindowTitle(_translate("watchdog", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("watchdog", "code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("watchdog", "market"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("watchdog", "name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("watchdog", "低价买入预警"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("watchdog", "高价卖出预警"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("watchdog", "实时价格"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("watchdog", "div10"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("watchdog", "预警是否弹窗"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("watchdog", "time"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("watchdog", "code"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("watchdog", "name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("watchdog", "成本价"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("watchdog", "数量"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("watchdog", "预卖价"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("watchdog", "现价"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("watchdog", "ht48"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("watchdog", "code"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("watchdog", "name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("watchdog", "成本价"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("watchdog", "数量"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("watchdog", "预卖价"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("watchdog", "现价"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("watchdog", "ht49"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("watchdog", "code"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("watchdog", "name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("watchdog", "成本价"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("watchdog", "数量"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("watchdog", "预卖价"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("watchdog", "现价"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("watchdog", "gs"))
        self.pushButton.setText(_translate("watchdog", "运行"))
        self.pushButton_2.setText(_translate("watchdog", "终止运行"))
        self.pushButton_4.setText(_translate("watchdog", "添加监控信息"))
        self.pushButton_5.setText(_translate("watchdog", "完成添加"))
        self.pushButton_3.setText(_translate("watchdog", "将表格信息存入csv"))
        self.pushButton_6.setText(_translate("watchdog", "更新持仓信息"))
        self.pushButton_7.setText(_translate("watchdog", "自动刷新"))
        self.pushButton_8.setText(_translate("watchdog", "手动刷新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    watchdog = QtWidgets.QWidget()
    ui = Ui_watchdog()
    ui.setupUi(watchdog)
    watchdog.show()
    sys.exit(app.exec_())

